export const dynamic = "force-dynamic";
export const runtime = "nodejs";

/**
 * GET /api/markers/[type] — streams a deterministic placeholder-marker PNG.
 *
 * `[type]` must be either `"qr"` or `"thumb"`. The PNG is generated by
 * `generateMarkerPng(type)` (in `src/lib/marker-placeholders.ts`) and is
 * byte-stable, so the response is marked cacheable for 24h.
 *
 * The user pastes these PNGs into their Google-Docs source template as
 * visual placeholders. At render time the worker swaps each one out by
 * matching its SHA-256 against the bytes embedded in `word/media/*`.
 *
 * Auth: required (via `requireUserApi`).
 */

import { NextRequest, NextResponse } from "next/server";
import { requireUserApi } from "@/lib/auth-guard";
import {
  generateMarkerPng,
  type MarkerType,
} from "@/lib/marker-placeholders";

const ALLOWED_TYPES: ReadonlyArray<MarkerType> = ["qr", "thumb"];

function isMarkerType(value: string): value is MarkerType {
  return (ALLOWED_TYPES as ReadonlyArray<string>).includes(value);
}

export async function GET(
  _req: NextRequest,
  { params }: { params: { type: string } },
) {
  const auth = await requireUserApi();
  if (!auth.ok) return auth.response;

  const type = params.type;
  if (!isMarkerType(type)) {
    return NextResponse.json(
      { error: "Ungültiger Marker-Typ. Erlaubt sind 'qr' und 'thumb'." },
      { status: 400 },
    );
  }

  try {
    const png = await generateMarkerPng(type);
    const filename = `videocomet-marker-${type}.png`;

    // Wrap the Buffer in a Blob — Node's Buffer extends Uint8Array but the
    // Next.js BodyInit type only accepts web-standard sources (string/Blob/
    // ReadableStream/FormData/URLSearchParams). This matches the pattern
    // used in `src/app/api/runs/[id]/export/route.ts`.
    //
    // We hand Blob a fresh ArrayBuffer copy because Node's
    // `Buffer<ArrayBufferLike>` isn't directly assignable to BlobPart
    // (TS distinguishes ArrayBuffer vs. SharedArrayBuffer at the type level).
    const ab = png.buffer.slice(
      png.byteOffset,
      png.byteOffset + png.byteLength,
    ) as ArrayBuffer;
    const blob = new Blob([ab], { type: "image/png" });

    return new NextResponse(blob, {
      status: 200,
      headers: {
        "Content-Type": "image/png",
        "Content-Disposition": `attachment; filename="${filename}"`,
        "Content-Length": String(png.byteLength),
        "Cache-Control": "public, max-age=86400",
      },
    });
  } catch (err) {
    console.error("[api/markers] generation failed:", err);
    return NextResponse.json(
      {
        error: "Marker konnte nicht erzeugt werden.",
        details: err instanceof Error ? err.message : null,
      },
      { status: 500 },
    );
  }
}
